# Generated by Django 2.2.16 on 2022-05-31 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20220601_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comments',
        ),
    ]
