# Generated by Django 2.2.28 on 2022-11-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Добавить аватарку', null=True, upload_to='users/', verbose_name='Аватарка'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
