# Generated by Django 2.2.16 on 2022-06-08 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220608_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Git'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/default.jpeg', null=True, upload_to='users/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VK'),
        ),
    ]
