# Generated by Django 2.2.16 on 2022-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Git'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/default.jpeg', null=True, upload_to='users/', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вконтакте'),
        ),
    ]
