# Generated by Django 2.2.16 on 2022-06-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220613_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/default.jpeg', help_text='Добавить аватарку', null=True, upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
