# Generated by Django 2.2.28 on 2022-11-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220613_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Добавить аватарку', null=True, upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
